Feat/hasegawa takashi/add create memo function
HasegawaTakashi/StudyPlanner pull request #23
Opened 2022-03-16 05:47 UTC by HasegawaTakashi

2022-03-16 23:35 UTC, oratake approved these changes
コメントかきましたー
本来であればRequest ChangeでPRが修正されるまでMergeできないようにするのですが、
今回は今修正するでもよいですし、Issueを切っておいてあとから修正でもよいとおもいますー

2022-03-16 23:35 UTC, oratake commented on app/Http/Controllers/CreateMemosController.php
> +        $posts = $request->all();
このあたりでバリデーションが入ると良さそうです。
https://readouble.com/laravel/8.x/ja/validation.html#quick-writing-the-validation-logic
2つぐらいならばcontroller内でやるで良いと思いますが、そのうち要素が増えてきたらControllerが煩雑になってくるので、
フォームリクエストを使うようにすると良いと思います。
ざっくりいうとartisanでバリデーションを含んだ独自のRequestクラスを切っておく感じです
https://readouble.com/laravel/8.x/ja/validation.html#form-request-validation
今回はControllerでvalidationを書くぐらいで良いと思います

バリデーションをかける内容としてはタイトルやメモの文字数で良いと思います

2022-03-16 23:38 UTC, oratake requested changes
すみません、レビュー通せなかった...
bladeだけは本番環境に移した場合動作しないコードになってしまうので、ここだけ修正は必須だと思います

あと文字数バリデーションもですね

2022-03-18 01:56 UTC, HasegawaTakashi commented on resources/views/dashboard.blade.php
> +        <a href="http://localhost/create-memo">
36a5ad78b565d9b1b4ff6e07a4a25c9b1164b408
上記コミットで修正しました。

生で動作確認し、後程名前付けをしようとして失念していました、ありがとうございます！

2022-03-18 01:57 UTC, HasegawaTakashi commented on routes/web.php
> +Route::get('/create-memo', [CreateMemosController::class, 'createMemo']);
36a5ad78b565d9b1b4ff6e07a4a25c9b1164b408
上記レビュー同様このコミットで修正いたしました。

2022-03-18 02:48 UTC, HasegawaTakashi commented on app/Http/Controllers/CreateMemosController.php
> +        ]);
809f857b7a65ac3cc9a3eef9220f613179452843
上記コミットで修正しました。
$fillableか$guardedどちらを使用するべきか迷いましたが、今回はカラムを指定するために$fillableを採用してみました。

2022-03-18 03:30 UTC, HasegawaTakashi commented on app/Http/Controllers/CreateMemosController.php
> +        $posts = $request->all();
b5a45b1881a57f9f416c470902af093fa9ff8e23
上記コミットで修正しました。
今後バリデーションをかける内容が増えてきたら上記の要領で編集しようと思います。

2022-03-18 03:34 UTC, merged